import type { BackgroundController } from './background.ts'
import type { Viewport } from './scene.ts'
import { getModels, type SceneModel, type Transform } from './scene-store.ts'

/** Three decimals is well past what the eye can judge and keeps the output readable. */
function num(value: number): string {
  const rounded = Number(value.toFixed(3))
  return Object.is(rounded, -0) ? '0' : String(rounded)
}

function vec(values: [number, number, number]): string {
  return `[${values.map(num).join(', ')}]`
}

function degrees(radians: [number, number, number]): string {
  return radians.map((value) => num((value * 180) / Math.PI)).join(', ')
}

export function readTransform(model: SceneModel): Transform {
  if (!model.object) {
    return model.savedTransform ?? { position: [0, 0, 0], rotation: [0, 0, 0], scale: [1, 1, 1] }
  }
  const { position, rotation, scale } = model.object
  return {
    position: [position.x, position.y, position.z],
    rotation: [rotation.x, rotation.y, rotation.z],
    scale: [scale.x, scale.y, scale.z],
  }
}

/**
 * Turns the current scene into a block that can be pasted straight into the real
 * site's source. Rotations are emitted in radians because that is what three
 * consumes, with the degrees in a trailing comment because that is what a person
 * reasons about.
 */
export function buildSnippet(viewport: Viewport, background: BackgroundController): string {
  const { camera, controls } = viewport
  const lines: string[] = []

  lines.push('// Generated by the constructor 3d playground.')
  lines.push('')
  lines.push(...backgroundLines(background))
  lines.push('')
  lines.push('export const CAMERA = {')
  lines.push(`  position: ${vec([camera.position.x, camera.position.y, camera.position.z])},`)
  lines.push(`  target: ${vec([controls.target.x, controls.target.y, controls.target.z])},`)
  lines.push(`  fov: ${num(camera.fov)},`)
  lines.push('}')
  lines.push('')
  lines.push('export const MODELS = [')

  for (const model of getModels()) {
    const transform = readTransform(model)

    if (model.origin === 'primitive') {
      lines.push(`  // ${model.name} (${model.id}) — scratch geometry, no file behind it`)
    } else if (model.origin === 'dropped') {
      lines.push(`  // ${model.id} — copy ${model.name} into public/models/ before using this`)
    } else {
      lines.push(`  // ${model.id}`)
    }

    lines.push('  {')
    // A primitive has no file, so emitting an empty src would only look broken
    // in the real site's source.
    if (model.src) lines.push(`    src: '${model.src}',`)
    lines.push(`    position: ${vec(transform.position)},`)
    lines.push(`    rotation: ${vec(transform.rotation)}, // degrees: ${degrees(transform.rotation)}`)
    lines.push(`    scale: ${vec(transform.scale)},`)
    lines.push('  },')
  }

  lines.push(']')
  lines.push('')

  return lines.join('\n')
}

/**
 * The backdrop is an equirectangular texture on `scene.background`, so the real
 * site reproduces it with the same three properties rather than any geometry of
 * its own — see background.ts for why there is no sphere mesh to rebuild.
 */
function backgroundLines(background: BackgroundController): string[] {
  const image = background.getImage()
  if (!image) return ['export const BACKGROUND = null']

  const settings = background.getSettings()
  const lines: string[] = []

  if (image.origin === 'dropped') {
    lines.push(`// copy ${image.name} into public/backgrounds/ before using this`)
  }

  lines.push('export const BACKGROUND = {')
  lines.push(`  src: '${image.src}',`)
  lines.push(
    `  rotation: ${vec([0, settings.rotationY, 0])}, // degrees: ${degrees([0, settings.rotationY, 0])}`,
  )
  if (!image.panoramic) lines.push(`  horizon: ${num(settings.horizon)},`)
  lines.push(`  blur: ${num(settings.blur)},`)
  lines.push(`  intensity: ${num(settings.intensity)},`)
  lines.push(`  lighting: ${settings.lighting},`)
  lines.push('}')

  return lines
}

/**
 * navigator.clipboard is unavailable outside a secure context, which includes
 * hitting the dev server on a LAN address from a phone — a normal thing to do
 * when checking how a scene reads on a small screen.
 */
export async function copyToClipboard(text: string): Promise<void> {
  if (navigator.clipboard && window.isSecureContext) {
    await navigator.clipboard.writeText(text)
    return
  }

  const scratch = document.createElement('textarea')
  scratch.value = text
  scratch.style.position = 'fixed'
  scratch.style.opacity = '0'
  document.body.append(scratch)
  scratch.select()
  const copied = document.execCommand('copy')
  scratch.remove()
  if (!copied) throw new Error('clipboard unavailable')
}
